version: '3.8'
services:
  service1:
    image: brightbee/monster1:latest
    build: ./api1/application
    ports:
    - target: 5000
      published: 5000
      protocol: tcp
  service2:
    image: brightbee/monster2:latest
    build: ./api2/application
    ports:
    - target: 5001
      published: 5001
      protocol: tcp
  service3:
    image: brightbee/monster3:latest
    build: ./api3/application
    ports:
    - target: 5002
      published: 5002
      protocol: tcp
  service4:
    image: brightbee/monster4:latest
    build: ./api4/application
    ports:
    - target: 5003
      published: 5003
      protocol: tcp